version: '3.8'

services:
  # データベース
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aimee_db
      MYSQL_USER: aimee
      MYSQL_PASSWORD: aimeepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://aimee:aimeepassword@db:3306/aimee_db
      AI_SERVICE_URL: http://ai:8001
    depends_on:
      db:
        condition: service_healthy
      ai:
        condition: service_started
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # AI Service (Llama)
  ai:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8001:8001"
    volumes:
      - ./models:/app/models
      - ./experiments/llama_rag_test:/app/ai_service
    environment:
      MODEL_PATH: /app/models/llama-2-7b-chat.Q4_K_M.gguf
    # GPUを使用する場合（ローカルではコメントアウト）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  db_data: