version: '3.9'

services:
  # MySQL データベース（aimee-db統合）
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8  # M3 Mac対応
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: aimee_db
      MYSQL_USER: aimee_user
      MYSQL_PASSWORD: Aimee2024!
    volumes:
      - mysql-data:/var/lib/mysql
      - ../aimee-db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../aimee-db/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
      - ../aimee-db/insert_operators.sql:/docker-entrypoint-initdb.d/03-insert_operators.sql
    command: >
      --innodb-buffer-pool-size=512M
      --max-connections=100
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

  # 軽量LLM専用コンテナ（qwen2:0.5b）
  ollama-light:
    image: ollama/ollama:latest
    platform: linux/arm64/v8
    ports:
      - "11433:11434"
    volumes:
      - ollama-light-models:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_ACCELERATION=metal  # Apple Silicon最適化
      - OLLAMA_MEMORY_LIMIT=3GB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3G
    restart: unless-stopped

  # メインLLM専用コンテナ（gemma3:4b）
  ollama-main:
    image: ollama/ollama:latest
    platform: linux/arm64/v8
    ports:
      - "11435:11434"
    volumes:
      - ollama-main-models:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_ACCELERATION=metal
      - OLLAMA_MEMORY_LIMIT=12GB
      - OLLAMA_BATCH_SIZE=256
      - OLLAMA_NUM_GPU_LAYERS=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 12G
    restart: unless-stopped

  # ChromaDB（ベクトルデータベース）
  chromadb:
    image: chromadb/chroma:latest
    platform: linux/arm64/v8
    ports:
      - "8003:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=token
      - CHROMA_SERVER_AUTH_CREDENTIALS=aimee-chroma-token
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
    # healthcheck disabled: コンテナにcurl/python3がないため
    # ChromaDBは起動していればOK (ポート8003で外部から確認可能)
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  # Redis（キャッシュ）
  redis:
    image: redis:7-alpine
    platform: linux/arm64/v8
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server 
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  # API (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    platform: linux/arm64/v8
    ports:
      - "8002:8002"
    environment:
      # データベース設定 (ローカルMySQLを使用)
      DATABASE_URL: mysql+aiomysql://aimee_user:Aimee2024!@host.docker.internal:3306/aimee_db
      # Redis設定
      REDIS_URL: redis://redis:6379/0
      # LLM設定
      OLLAMA_LIGHT_HOST: ollama-light
      OLLAMA_LIGHT_PORT: 11434
      OLLAMA_MAIN_HOST: ollama-main
      OLLAMA_MAIN_PORT: 11434
      # ChromaDB設定
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8000
      CHROMADB_AUTH_TOKEN: aimee-chroma-token
      # アプリケーション設定
      INTENT_MODEL: qwen2:0.5b
      MAIN_MODEL: gemma3:4b
      ENABLE_PARALLEL_PROCESSING: "true"
      STREAMING_RESPONSE: "true"
      # セキュリティ
      SECRET_KEY: Ong4L4vAmW6EgSsQvVIYPfJZ3qzk1LEvFvVaJRVX3SvTRQD6kBOUrUC4u8kYtH86
    env_file:
      - .env
    # env_fileの設定を環境変数でオーバーライド可能にする
    extra_hosts:
      # ローカルMySQLに接続するため
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - ollama-light
      - ollama-main
      - chromadb
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
  chroma-data:
    driver: local
  redis-data:
    driver: local
  ollama-light-models:
    driver: local
  ollama-main-models:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16